services:
  postgres:
    image: postgres:15.7-alpine
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5432:5432
    expose:
      - "5432"
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    environment:
      - PYTHONPATH: .
      - DATABASE_URL=$DATABASE_URL
    depends_on:
      - "postgres"
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app